version: "2"
services:
  integration-deps:
    image: busybox
    depends_on:
    - price
    - redis
    - mongodb
    - bitcoind
    - lnd1
    - lnd2
    - lnd-outside-1
    - lnd-outside-2
    - otel-agent
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.43.0
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
    - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
    - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    volumes:
      - ./dev/otel-agent-config.yaml:/etc/otel-agent-config.yaml
  price:
    image: us.gcr.io/galoy-org/price:edge
  redis:
    image: bitnami/redis:6.2
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  mongodb-migrate:
    depends_on: [mongodb]
    build:
      context: .
      dockerfile: Dockerfile-migrate
    environment:
    - MONGODB_ADDRESS=mongodb
  mongodb:
    image: bitnami/mongodb:4.4.6-debian-10-r0
    environment:
    - MONGODB_PASSWORD=password
    - MONGODB_USERNAME=testGaloy
    - MONGODB_DATABASE=galoy
    - MONGODB_REPLICA_SET_MODE=primary
    - MONGODB_ROOT_PASSWORD=password
    - MONGODB_REPLICA_SET_KEY=replicasetkey
  bitcoind:
    image: lncm/bitcoind:v22.0
    volumes:
    - ${PWD}/dev/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
  lnd1:
    image: lightninglabs/lnd:v0.14.3-beta
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
    depends_on: [bitcoind]
  lnd2:
    image: lightninglabs/lnd:v0.14.3-beta
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
    depends_on: [bitcoind]
  lnd-outside-1:
    image: lightninglabs/lnd:v0.14.3-beta
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
    depends_on: [bitcoind]
  lnd-outside-2:
    image: lightninglabs/lnd:v0.14.3-beta
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
    depends_on: [bitcoind]
  loopserver:
    image: lightninglabs/loopserver:v0.9.50-beta
    restart: unless-stopped
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/macaroons/lnd1:/root/.lnd/data/chain/bitcoin/regtest
    depends_on: [lnd1]
    command:
      - "daemon"
      - "--maxamt=5000000"
      - "--lnd.host=lnd1:10009"
      - "--lnd.macaroondir=/root/.lnd/data/chain/bitcoin/regtest"
      - "--lnd.tlspath=/root/.lnd/tls.cert"
  loopclient:
    image: lightninglabs/loop:v0.19.1-beta
    restart: unless-stopped
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/macaroons/lnd2:/root/.lnd/data/chain/bitcoin/regtest
    depends_on: [loopserver]
    command:
      - "loopd"
      - "--network=regtest"
      - "--debuglevel=debug"
      - "--server.host=loopserver:11009"
      - "--server.notls"
      - "--lnd.host=lnd2:10010"
      - "--lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
      - "--lnd.tlspath=/root/.lnd/tls.cert"
  e2e-tests:
    image: us.gcr.io/galoy-org/galoy-app-pipeline
    depends_on:
    - integration-deps
    command: ["make","execute-e2e-from-within-container"]
    working_dir: /repo
    env_file:
      - ${TMP_ENV_CI:-.env.ci}
    volumes:
      - ./:/repo
  integration-tests:
    image: us.gcr.io/galoy-org/galoy-app-pipeline
    depends_on:
    - integration-deps
    command: ["make","execute-integration-from-within-container"]
    working_dir: /repo
    env_file:
      - ${TMP_ENV_CI:-.env.ci}
    volumes:
      - ./:/repo
